
// Resource paths that can be used in permissions
export const RESOURCE_PATHS = [
  "/client-area",
  "/client-area/bluebay",
  "/client-area/bluebay/jab-orders",
  "/client-area/bluebay/aprovacao-financeira",
  "/client-area/bluebay/acompanhamento-faturamento",
  "/client-area/bluebay_adm",
  "/client-area/bluebay_adm/reports",
  "/client-area/bluebay_adm/dashboard",
  "/client-area/bluebay_adm/clients",
  "/client-area/bluebay_adm/financial",
  "/client-area/bluebay_adm/estoque",
  "/client-area/bluebay_adm/annalisedecompra",
  "/client-area/bluebay_adm/pedidos",
  "/client-area/bluebay_adm/item-management", 
  "/client-area/bluebay_adm/financeiromanager",
  "/client-area/bluebay_adm/requests",
  "/client-area/bk",
  "/client-area/bk/clients",
  "/client-area/bk/financial",
  "/client-area/bk/reports",
  "/client-area/bk/dashboard",
  "/client-area/bk/gestaotitulos",
  "/client-area/bk/financeiromanager",
  "/client-area/bk/clientefinancial",
  "/client-area/bk/estoque", 
  "/client-area/bk/requests",
  "/client-area/bk/invoice-control",
  "/client-area/bk/pedidos",
  // Oni Agência routes
  "/client-area/oniagencia",
  "/client-area/oniagencia/controle-pauta",
  "/client-area/oniagencia/clientes",
  "/client-area/oniagencia/servicos",
  "/client-area/oniagencia/colaboradores",
  "/client-area/oniagencia/relatorios",
  "/client-area/content-management",
  "/client-area/mailing-registration",
  "/client-area/tokens",
  "/client-area/whatsapp-registration",
  "/client-area/whatsapp",
  "/client-area/representantes",
  "/admin",
  "/admin/banners",
  "/admin/clients",
  "/admin/groups",
  "/admin/permissions",
  "/admin/users",
  "/admin/requests",
  "/admin/sub-themes",
  "/admin/logos",
  "/admin/messages",
  "/admin/seo",
  "/admin/services",
  "/admin/social",
  "/post-management"
];

// Alias for RESOURCE_PATHS to maintain backward compatibility
export const KNOWN_ROUTES = RESOURCE_PATHS;
