// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwvrxtvlqkttylfzzxas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dnJ4dHZscWt0dHlsZnp6eGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NTQ3NzQsImV4cCI6MjA1MjAzMDc3NH0.4HQUx3BPPPk-i-9EPlVdkxGu_GRfSDzQNyoq7fss-aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);