import {
  Monitor,
  Laptop,
  Users,
  Video,
  Share2,
  BarChart,
  Camera,
  Image,
  Mic,
  Music,
  Paintbrush,
  Settings,
  Wrench,
  BookOpen,
  Brain,
  Briefcase,
  Building,
  CircleDollarSign,
  Cog,
  FileText,
  Fingerprint,
  Gauge,
  HeartHandshake,
  LayoutDashboard,
  LineChart,
  MessageSquare,
  Microscope,
  PenTool,
  Presentation,
  Rocket,
  Search,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Target,
  Zap,
} from "lucide-react";

export const icons = [
  { name: "Monitor", icon: <Monitor className="w-4 h-4" /> },
  { name: "Laptop", icon: <Laptop className="w-4 h-4" /> },
  { name: "Users", icon: <Users className="w-4 h-4" /> },
  { name: "Video", icon: <Video className="w-4 h-4" /> },
  { name: "Share2", icon: <Share2 className="w-4 h-4" /> },
  { name: "BarChart", icon: <BarChart className="w-4 h-4" /> },
  { name: "Camera", icon: <Camera className="w-4 h-4" /> },
  { name: "Image", icon: <Image className="w-4 h-4" /> },
  { name: "Mic", icon: <Mic className="w-4 h-4" /> },
  { name: "Music", icon: <Music className="w-4 h-4" /> },
  { name: "Paintbrush", icon: <Paintbrush className="w-4 h-4" /> },
  { name: "Settings", icon: <Settings className="w-4 h-4" /> },
  { name: "Wrench", icon: <Wrench className="w-4 h-4" /> },
  { name: "BookOpen", icon: <BookOpen className="w-4 h-4" /> },
  { name: "Brain", icon: <Brain className="w-4 h-4" /> },
  { name: "Briefcase", icon: <Briefcase className="w-4 h-4" /> },
  { name: "Building", icon: <Building className="w-4 h-4" /> },
  { name: "CircleDollarSign", icon: <CircleDollarSign className="w-4 h-4" /> },
  { name: "Cog", icon: <Cog className="w-4 h-4" /> },
  { name: "FileText", icon: <FileText className="w-4 h-4" /> },
  { name: "Fingerprint", icon: <Fingerprint className="w-4 h-4" /> },
  { name: "Gauge", icon: <Gauge className="w-4 h-4" /> },
  { name: "HeartHandshake", icon: <HeartHandshake className="w-4 h-4" /> },
  { name: "LayoutDashboard", icon: <LayoutDashboard className="w-4 h-4" /> },
  { name: "LineChart", icon: <LineChart className="w-4 h-4" /> },
  { name: "MessageSquare", icon: <MessageSquare className="w-4 h-4" /> },
  { name: "Microscope", icon: <Microscope className="w-4 h-4" /> },
  { name: "PenTool", icon: <PenTool className="w-4 h-4" /> },
  { name: "Presentation", icon: <Presentation className="w-4 h-4" /> },
  { name: "Rocket", icon: <Rocket className="w-4 h-4" /> },
  { name: "Search", icon: <Search className="w-4 h-4" /> },
  { name: "ShieldCheck", icon: <ShieldCheck className="w-4 h-4" /> },
  { name: "Smartphone", icon: <Smartphone className="w-4 h-4" /> },
  { name: "Sparkles", icon: <Sparkles className="w-4 h-4" /> },
  { name: "Target", icon: <Target className="w-4 h-4" /> },
  { name: "Zap", icon: <Zap className="w-4 h-4" /> },
];